# Site settings
remote_theme  : mmistakes/so-simple-theme
title         : [Stan George]
description   : [stanleygeorge.com]
url           :  https://stanleygeorge.com
read_time: true
words_per_minute: 200

# Taxonomy pages
category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"

plugins       :
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate  

#Collections
collections   :
  articles    :
    output    : true
    permalink : /:collection/:path
  books       :
    output    : true
    permalink : /:collection/:path


# Site Author
author:
  name: 
  picture:
  email: 
  twitter:
  links:
    - title:
      url: 
      icon:
      
# Footer Links
footer_links:
  - title: Feed
    url: atom.xml
    icon: fas fa-rss-square
