remote_theme  : mmistakes/so-simple-theme
title         : [Stan George]
description   : [stanleygeorge.com]
url           :  https://stanleygeorge.com
plugins       :
  - jekyll-include-cache
collections   :
  articles    :
    output    : true
    permalink : /:collection/:path
  books       :
    output    : true
    permalink : /:collection/:path

# Site Author
author:
  name: Stan George
  picture:
  email: stanleygeorge@gmail.com
  twitter:
  links:
    - title:
      url: https://stanleygeorge.com
      icon:
      
# Footer Links
footer_links:
  - title: Feed
    url: atom.xml
    icon: fas fa-rss-square
