theme         : jekyll-theme-minimal
title         : [Stan George]
description   : [stanleygeorge.com]
collections   :
  articles    :
    output    : true
    permalink : /:collection/:path
  books       :
    output    : true
    permalink : /:collection/:path
