# theme         : jekyll-theme-minimal
remote_theme  : "mmistakes/minimal-mistakes@4.17.2" 
title         : [Stan George]
description   : [stanleygeorge.com]
collections   :
  articles    :
    output    : true
    permalink : /:collection/:path
  books       :
    output    : true
    permalink : /:collection/:path
