theme         : jekyll-theme-minimal
title         : [Stan George]
description   : [stanleygeorge.com]
collections   :
  articles    :
    output    : true
    permalink : /:collection/:path
  books       :
    output    : true
    permalink : /:collection/:path
atom_feed     :
  path        : atom.xml

# Site Author
author:
  name             : "Stan George"
  avatar           : "stan.jpg"
  location         : "Chicago"

# Site Footer
footer:
  links:
    - label: "RSS"
      icon: 
      url: atom.xml
