# theme         : jekyll-theme-minimal
remote_theme  : mmistakes/so-simple-theme
title         : [Stan George]
description   : [stanleygeorge.com]
plugins       :
  - jekyll-include-cache
collections   :
  articles    :
    output    : true
    permalink : /:collection/:path
  books       :
    output    : true
    permalink : /:collection/:path
